//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UfimtsevUchPractica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.OrderCar = new HashSet<OrderCar>();
        }
    
        public int CarID { get; set; }
        public int ModelID { get; set; }
        public string VIN { get; set; }
        public int ReleaseYear { get; set; }
        public string PTS { get; set; }
        public string Price { get; set; }
        public int StatusID { get; set; }
        public string CarImage { get; set; }
    
        public virtual CarStatus CarStatus { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCar> OrderCar { get; set; }

        public string imgPath
        {
            get
            {
                var path = "D:\\VSProjects\\UfimtsevUchPractica\\UfimtsevUchPractica\\Resources\\" + this.CarImage;
                return path;
            }
        }

        public string Status
        {
            get
            {
                if (StatusID == 1)
                {
                    return "Куплена";
                }

                else
                {
                    return "Продается";
                }
            }
        }
    }
}
