//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UfimtsevUchPractica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCar
    {
        public int OrderID { get; set; }
        public int CarID { get; set; }
        public int CountCar { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Order Order { get; set; }
    }
}
